### PR TITLE
Add Saucelabs tests for browser client demo

### LINKED ISSUE #2: Test in more browsers
Currently it is only tested in Chrome.

### LINKED ISSUE #4: Can we us Travis-CI or similar for this?
It would be nice to have continuous integration, but I am not sure how to since testing involves logging in...

### PR DESCRIPTION
**Pull request by awlayton**
This adds tests for getting ID and access tokens with the in-browser version of the library.

The Saucelabs tests finally seem repeatable. Safari is weird sometimes still, but I think it's good enough for now. Travis is set to run the tests in the latest Chrome, Firefox, IE, and Safari.

I would say this resolves #4 and resolves #2.

### CODE REVIEW

**Comment by abalmos** [comment]
@awlayton Seems like the tests break in Travis

**Comment by awlayton** [comment]
They just broken period. Not sure how that step got lost...

**Comment by awlayton** [comment]
Now that IE bug with finding elements is showing up again...

**Comment by awlayton** [comment]
Good enough for now, I'm merging it and moving on.

**Pull request merged**
